# Copyright 2025 Simone Rubino
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from lxml import etree

from .common import Common


class TestExport(Common):
    def _render_dati_generali(self, invoice):
        """Return the DatiGenerali node of the XML exported for `invoice`."""
        invoice_etree = etree.fromstring(invoice._l10n_it_edi_render_xml())
        return invoice_etree.find(".//DatiGenerali")

    def test_narration(self):
        """The narration included in the invoice
        is exported to the XML in Causale nodes."""
        invoice = self.init_invoice(
            "out_invoice",
            amounts=[100],
            company=self.company,
            partner=self.italian_partner_a,
            taxes=self.default_tax,
        )
        invoice.invoice_date_due = invoice.date
        invoice.narration = "first line\n\nsecond line"
        invoice.action_post()
        self._assert_export_invoice(invoice, "narration.xml")

    def test_partner_shipping(self):
        """The partner shipping included in the invoice
        is exported to the XML in IndirizzoResa node."""
        invoice = self.init_invoice(
            "out_invoice",
            amounts=[100],
            company=self.company,
            partner=self.italian_partner_a,
            taxes=self.default_tax,
        )
        invoice.invoice_date_due = invoice.date
        invoice.partner_shipping_id = self.italian_shipping_partner_a
        invoice.action_post()
        self._assert_export_invoice(invoice, "partner_shipping.xml")

    def test_partner_shipping_is_last_in_dati_generali(self):
        """DatiTrasporto is exported after the other DatiGenerali children.

        In the XSD sequence DatiTrasporto is the second to last element:
        exporting it right after DatiGeneraliDocumento makes every following
        element (here DatiOrdineAcquisto, generated by the core out of `ref`)
        invalid.
        """
        invoice = self.init_invoice(
            "out_invoice",
            amounts=[100],
            company=self.company,
            partner=self.italian_partner_a,
            taxes=self.default_tax,
        )
        invoice.invoice_date_due = invoice.date
        invoice.partner_shipping_id = self.italian_shipping_partner_a
        invoice.ref = "PO/2019/0001"
        invoice.action_post()

        dati_generali = self._render_dati_generali(invoice)
        self.assertEqual(
            [child.tag for child in dati_generali],
            [
                "DatiGeneraliDocumento",
                "DatiOrdineAcquisto",
                "DatiTrasporto",
            ],
        )

    def test_foreign_partner_shipping(self):
        """A foreign delivery address is normalized like the core does for Sede.

        Foreign countries are not mapped by the Tax Agency, so CAP is fixed at
        '00000' and Provincia is not exported at all.
        """
        invoice = self.init_invoice(
            "out_invoice",
            amounts=[100],
            company=self.company,
            partner=self.italian_partner_a,
            taxes=self.default_tax,
        )
        invoice.invoice_date_due = invoice.date
        invoice.partner_shipping_id = self.foreign_shipping_partner_a
        invoice.action_post()

        indirizzo_resa = self._render_dati_generali(invoice).find(
            "DatiTrasporto/IndirizzoResa"
        )
        self.assertEqual(indirizzo_resa.findtext("CAP"), "00000")
        self.assertEqual(indirizzo_resa.findtext("Nazione"), "US")
        self.assertIsNone(indirizzo_resa.find("Provincia"))
